# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build demo app"
  lane :build do
    gym(project: "FastlanePluginDemo/FastlanePluginDemo.xcodeproj", scheme: "FastlanePluginDemo", export_method: "development")
    instabug_official(api_token: "<Instabug token>")
  end

  lane :refresh_dsyms do
    download_dsyms(version: "latest")
    instabug_official(api_token: "<Instabug token>")
  end
end